<?php

use Drupal\multiversion\Entity\Workspace;

/**
 * Implements hook_modules_installed()
 *
 * Enables moderation for the default workspace entity
 */
function lightning_preview_modules_installed() {
  $container = \Drupal::getContainer();
  $workspace_manager = $container->get('workspace.manager');

  // Make the "basic" Workspace moderatable.
  $workspace_type_storage = \Drupal::entityManager()->getStorage('workspace_type');
  $workspace_type = $workspace_type_storage->load('basic');
  $workspace_type->setThirdPartySetting('workbench_moderation', 'enabled', TRUE);
  $workspace_type->setThirdPartySetting('workbench_moderation', 'allowed_moderation_states', ['draft', 'needs_review', 'published']);
  $workspace_type->setThirdPartySetting('workbench_moderation', 'default_moderation_state', 'draft');
  $workspace_type->save();
}

